version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile.dev
    ports:
      - "3002:3002"
    extra_hosts:
      - "host.docker.internal:host-gateway"
    env_file:
      - .env  
    volumes:
      - .:/app                
    command: npm run dev